import json
import os
import unittest
from pathlib import Path
from unittest.mock import patch

from awb.core.planner import propose_manifest
from awb.templates.templates import custom_manifest, research_manifest, software_manifest


EXPECTED = {
    'director': 'qwen3:4b',
    'worker': 'qwen3:4b',
    'reviewer': 'llama3.2:3b',
    'verifier': 'gemma3:4b',
}


def role_models(manifest):
    return {a['role']: a['provider']['model'] for a in manifest['agents']}


class FakePlannerProvider:
    def generate(self, system: str, user: str) -> str:
        return json.dumps({
            'type': 'research',
            'description': 'Generated by local planner',
            'agents': [
                {'id': 'dir', 'role': 'director', 'instructions': 'direct'},
                {'id': 'worker', 'role': 'worker', 'instructions': 'build'},
                {'id': 'critic', 'role': 'reviewer', 'instructions': 'attack'},
                {'id': 'check', 'role': 'verifier', 'instructions': 'verify'},
            ],
            'gates': [
                {'id': 'done', 'description': 'objective evidence exists', 'required': True, 'manual': False},
            ],
        })


class MultiModelDefaultTests(unittest.TestCase):
    def test_all_templates_use_heterogeneous_role_models(self):
        with patch.dict(os.environ, {}, clear=True):
            for factory in (research_manifest, software_manifest, custom_manifest):
                manifest = factory('demo', 'finish the goal')
                models = role_models(manifest)
                self.assertEqual(models, EXPECTED)
                self.assertEqual(len(set(models.values())), 3)

    def test_planner_generated_agents_keep_role_model_diversity(self):
        with patch.dict(os.environ, {}, clear=True), patch(
            'awb.core.planner.make_provider', return_value=FakePlannerProvider()
        ):
            manifest = propose_manifest(
                'Obtain a rigorous theorem result',
                name='paper',
                use_local_ai=True,
            )
        self.assertEqual(role_models(manifest), EXPECTED)

    def test_role_specific_model_overrides_do_not_collapse_other_roles(self):
        env = {
            'AWB_WORKER_MODEL': 'qwen-custom:4b',
            'AWB_DIRECTOR_MODEL': 'qwen-director:4b',
            'AWB_REVIEWER_MODEL': 'llama-custom:3b',
            'AWB_VERIFIER_MODEL': 'gemma-custom:4b',
        }
        with patch.dict(os.environ, env, clear=True):
            models = role_models(custom_manifest('demo', 'finish'))
        self.assertEqual(models['worker'], 'qwen-custom:4b')
        self.assertEqual(models['director'], 'qwen-director:4b')
        self.assertEqual(models['reviewer'], 'llama-custom:3b')
        self.assertEqual(models['verifier'], 'gemma-custom:4b')

    def test_bootstrap_requires_the_three_default_models_and_disk_budget(self):
        repo = Path(__file__).resolve().parents[1]
        for filename in ('first-run.sh', 'first-run.ps1'):
            text = (repo / filename).read_text()
            for model in ('qwen3:4b', 'llama3.2:3b', 'gemma3:4b'):
                self.assertIn(model, text)
            self.assertIn('20', text)

        compose = (repo / 'docker-compose.yml').read_text()
        self.assertIn('OLLAMA_MAX_LOADED_MODELS=${OLLAMA_MAX_LOADED_MODELS:-1}', compose)


if __name__ == '__main__':
    unittest.main()
