import json
import os
import unittest
from pathlib import Path
from unittest.mock import patch

from awb.core.planner import propose_manifest
from awb.templates.templates import custom_manifest, research_manifest, software_manifest


EXPECTED = {
    'director': 'qwen3:4b',
    'worker': 'qwen3:4b',
    'reviewer': 'qwen3:4b',
    'verifier': 'qwen3:4b',
}


def role_models(manifest):
    return {a['role']: a['provider']['model'] for a in manifest['agents']}


class FakePlannerProvider:
    def generate(self, system: str, user: str) -> str:
        return json.dumps({
            'type': 'research',
            'description': 'Generated by local planner',
            'agents': [
                {'id': 'dir', 'role': 'director', 'instructions': 'direct'},
                {'id': 'worker', 'role': 'worker', 'instructions': 'build'},
                {'id': 'critic', 'role': 'reviewer', 'instructions': 'attack'},
                {'id': 'check', 'role': 'verifier', 'instructions': 'verify'},
            ],
            'gates': [
                {'id': 'done', 'description': 'objective evidence exists', 'required': True, 'manual': False},
            ],
        })


class MultiModelDefaultTests(unittest.TestCase):
    def test_all_templates_use_one_resident_acepc_model(self):
        with patch.dict(os.environ, {}, clear=True):
            for factory in (research_manifest, software_manifest, custom_manifest):
                manifest = factory('demo', 'finish the goal')
                models = role_models(manifest)
                self.assertEqual(models, EXPECTED)
                self.assertEqual(set(models.values()), {'qwen3:4b'})
                self.assertEqual(manifest['runtime']['scheduler']['queue_timeout_seconds'], 0.0)
                self.assertEqual(manifest['runtime']['continuous_session_minutes'], 0)
                self.assertGreaterEqual(manifest['runtime']['max_tool_calls_per_task'], 50)

    def test_planner_generated_agents_keep_single_model_role_prompts(self):
        with patch.dict(os.environ, {}, clear=True), patch(
            'awb.core.planner.make_provider', return_value=FakePlannerProvider()
        ):
            manifest = propose_manifest(
                'Obtain a rigorous theorem result',
                name='paper',
                use_local_ai=True,
            )
        self.assertEqual(role_models(manifest), EXPECTED)

    def test_role_specific_model_overrides_remain_possible_for_future_hardware(self):
        env = {
            'AWB_WORKER_MODEL': 'qwen-custom:4b',
            'AWB_DIRECTOR_MODEL': 'qwen-director:4b',
            'AWB_REVIEWER_MODEL': 'llama-custom:3b',
            'AWB_VERIFIER_MODEL': 'gemma-custom:4b',
        }
        with patch.dict(os.environ, env, clear=True):
            models = role_models(custom_manifest('demo', 'finish'))
        self.assertEqual(models['worker'], 'qwen-custom:4b')
        self.assertEqual(models['director'], 'qwen-director:4b')
        self.assertEqual(models['reviewer'], 'llama-custom:3b')
        self.assertEqual(models['verifier'], 'gemma-custom:4b')

    def test_bootstrap_and_compose_enforce_one_loaded_model(self):
        repo = Path(__file__).resolve().parents[1]
        compose = (repo / 'docker-compose.yml').read_text()
        self.assertIn('OLLAMA_MAX_LOADED_MODELS=${OLLAMA_MAX_LOADED_MODELS:-1}', compose)
        self.assertIn('OLLAMA_NUM_PARALLEL=${OLLAMA_NUM_PARALLEL:-1}', compose)
        self.assertIn('AWB_REVIEWER_MODEL=${AWB_REVIEWER_MODEL:-qwen3:4b}', compose)
        self.assertIn('AWB_STREAM_TRACE_DIR=/data/workspaces/.awb-streams', compose)


if __name__ == '__main__':
    unittest.main()
